<?php
/**
 * @file
 * Code for the VIH_Lectures feature.
 */

include_once('vih_lectures.features.inc');

function vih_lectures_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'VIHLecturesProduct' => array('class_name' => 'VIHLecturesProduct'),
      'VIHLecturesNode' => array('class_name' => 'VIHLecturesNode'),
    ),
  );
  return $api;
}

/**
 * Implements hook_admin_paths().
 */
function vih_lectures_admin_paths() {
  $paths = array(
    'node/*/emails' => TRUE,
    'node/*/tilmeldinger' => TRUE,
  );
  return $paths;
}
